export const styles = {
  root: {
    minHeight: "100vh",
    background: "#fafafa",
    fontFamily: "'DM Sans', 'Helvetica Neue', sans-serif",
    color: "#111",
  },
  header: {
    position: "sticky",
    top: 0,
    zIndex: 100,
    background: "rgba(250,250,250,0.92)",
    backdropFilter: "blur(12px)",
    borderBottom: "1px solid #ebebeb",
    padding: "0 24px",
  },
  headerInner: {
    maxWidth: 1400,
    margin: "0 auto",
    display: "flex",
    alignItems: "center",
    gap: 16,
    height: 64,
  },
  logo: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    flexShrink: 0,
  },
  logoMark: {
    fontSize: 20,
    color: "#111",
  },
  logoText: {
    fontSize: 18,
    fontWeight: 700,
    letterSpacing: "-0.5px",
    color: "#111",
  },
  searchWrap: {
    flex: 1,
    position: "relative",
    display: "flex",
    alignItems: "center",
    background: "#f0f0f0",
    borderRadius: 10,
    padding: "0 12px",
    maxWidth: 480,
  },
  searchIcon: {
    fontSize: 18,
    color: "#999",
    marginRight: 8,
    lineHeight: 1,
  },
  searchInput: {
    flex: 1,
    border: "none",
    background: "transparent",
    fontSize: 14,
    color: "#111",
    outline: "none",
    padding: "10px 0",
    fontFamily: "inherit",
  },
  clearBtn: {
    background: "none",
    border: "none",
    cursor: "pointer",
    fontSize: 18,
    color: "#999",
    padding: "0 4px",
    lineHeight: 1,
  },
  favToggle: {
    display: "flex",
    alignItems: "center",
    gap: 6,
    background: "none",
    border: "1.5px solid #ddd",
    borderRadius: 8,
    padding: "7px 14px",
    cursor: "pointer",
    fontSize: 16,
    color: "#666",
    fontFamily: "inherit",
    transition: "all 0.2s",
    flexShrink: 0,
  },
  favToggleActive: {
    background: "#111",
    borderColor: "#111",
    color: "#fff",
  },
  favCount: {
    fontSize: 13,
    fontWeight: 600,
  },
  categories: {
    maxWidth: 1400,
    margin: "0 auto",
    display: "flex",
    gap: 8,
    padding: "10px 0 12px",
    overflowX: "auto",
    scrollbarWidth: "none",
  },
  catBtn: {
    background: "none",
    border: "1.5px solid #e0e0e0",
    borderRadius: 20,
    padding: "5px 14px",
    fontSize: 13,
    fontWeight: 500,
    color: "#666",
    cursor: "pointer",
    whiteSpace: "nowrap",
    fontFamily: "inherit",
    transition: "all 0.15s",
  },
  catBtnActive: {
    background: "#111",
    borderColor: "#111",
    color: "#fff",
  },
  notice: {
    textAlign: "center",
    background: "#fff8e1",
    color: "#7a6000",
    fontSize: 13,
    padding: "10px 16px",
    borderBottom: "1px solid #ffe082",
  },
  main: {
    maxWidth: 1400,
    margin: "0 auto",
    padding: "28px 24px 60px",
  },
  grid: {
    columns: "repeat(auto-fill, minmax(200px, 1fr))",
    columnGap: 16,
    rowGap: 16,
    display: "grid",
    gridTemplateColumns: "repeat(auto-fill, minmax(200px, 1fr))",
  },
  card: {
    position: "relative",
    borderRadius: 14,
    overflow: "hidden",
    background: "#eee",
    aspectRatio: "9 / 16",
    cursor: "pointer",
    transition: "transform 0.2s ease, box-shadow 0.2s ease",
    boxShadow: "0 2px 8px rgba(0,0,0,0.06)",
  },
  cardHover: {
    transform: "translateY(-4px) scale(1.01)",
    boxShadow: "0 12px 32px rgba(0,0,0,0.12)",
  },
  imgWrap: {
    width: "100%",
    height: "100%",
    position: "relative",
  },
  imgPlaceholder: {
    position: "absolute",
    inset: 0,
    transition: "opacity 0.3s",
  },
  img: {
    width: "100%",
    height: "100%",
    objectFit: "cover",
    transition: "opacity 0.4s ease",
    display: "block",
  },
  cardOverlay: {
    position: "absolute",
    inset: 0,
    background: "linear-gradient(to top, rgba(0,0,0,0.55) 0%, transparent 50%)",
    display: "flex",
    flexDirection: "column",
    justifyContent: "flex-end",
    padding: 12,
    transition: "opacity 0.2s",
    pointerEvents: "none",
  },
  previewBtn: {
    background: "rgba(255,255,255,0.15)",
    backdropFilter: "blur(8px)",
    border: "1px solid rgba(255,255,255,0.3)",
    borderRadius: 8,
    color: "#fff",
    fontSize: 12,
    fontWeight: 600,
    padding: "6px 0",
    cursor: "pointer",
    fontFamily: "inherit",
    letterSpacing: "0.3px",
    pointerEvents: "auto",
    marginBottom: 8,
  },
  cardIcons: {
    display: "flex",
    gap: 8,
    pointerEvents: "auto",
  },
  iconBtn: {
    width: 32,
    height: 32,
    borderRadius: 8,
    background: "rgba(255,255,255,0.15)",
    backdropFilter: "blur(8px)",
    border: "1px solid rgba(255,255,255,0.25)",
    color: "#fff",
    fontSize: 16,
    cursor: "pointer",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    lineHeight: 1,
    transition: "background 0.15s",
  },
  iconBtnFav: {
    background: "rgba(220,50,50,0.7)",
    borderColor: "rgba(220,50,50,0.5)",
  },
  loadMore: {
    display: "flex",
    justifyContent: "center",
    padding: "40px 0 0",
  },
  spinner: {
    width: 28,
    height: 28,
    borderRadius: "50%",
    border: "2.5px solid #ddd",
    borderTopColor: "#111",
    animation: "spin 0.7s linear infinite",
  },
  empty: {
    textAlign: "center",
    padding: "100px 0",
  },
  emptyIcon: {
    fontSize: 48,
    color: "#ddd",
    marginBottom: 16,
  },
  emptyText: {
    fontSize: 18,
    fontWeight: 600,
    color: "#333",
    margin: "0 0 8px",
  },
  emptySubtext: {
    fontSize: 14,
    color: "#999",
    margin: 0,
  },
  overlay: {
    position: "fixed",
    inset: 0,
    background: "rgba(0,0,0,0.85)",
    zIndex: 1000,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    padding: 24,
    backdropFilter: "blur(6px)",
  },
  overlayContent: {
    position: "relative",
    maxHeight: "90vh",
    maxWidth: 480,
    width: "100%",
    borderRadius: 20,
    overflow: "hidden",
    background: "#111",
    boxShadow: "0 40px 80px rgba(0,0,0,0.6)",
  },
  previewImg: {
    width: "100%",
    maxHeight: "75vh",
    objectFit: "cover",
    display: "block",
  },
  previewBar: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    padding: "14px 18px",
    background: "#111",
  },
  previewName: {
    margin: 0,
    fontSize: 14,
    fontWeight: 600,
    color: "#fff",
  },
  previewDesc: {
    margin: "3px 0 0",
    fontSize: 12,
    color: "#888",
    textTransform: "capitalize",
  },
  previewActions: {
    display: "flex",
    gap: 10,
  },
  actionBtn: {
    width: 40,
    height: 40,
    borderRadius: 10,
    background: "#222",
    border: "1px solid #333",
    color: "#aaa",
    fontSize: 18,
    cursor: "pointer",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    transition: "all 0.15s",
  },
  actionBtnFav: {
    color: "#e74c3c",
    background: "#2a1515",
    borderColor: "#4a2020",
  },
  actionBtnDl: {
    color: "#fff",
    background: "#1a1a1a",
  },
  closeBtn: {
    position: "absolute",
    top: 14,
    right: 14,
    width: 34,
    height: 34,
    borderRadius: "50%",
    background: "rgba(0,0,0,0.6)",
    border: "1px solid rgba(255,255,255,0.15)",
    color: "#fff",
    fontSize: 20,
    cursor: "pointer",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    lineHeight: 1,
    backdropFilter: "blur(4px)",
  },
};
