export const styles = {
  root: {
    minHeight: "100vh",
    background: "var(--bg)",
    fontFamily: "'DM Sans', 'Helvetica Neue', sans-serif",
    color: "var(--text)",
    transition: "background 0.3s, color 0.3s",
  },
  header: {
    position: "sticky",
    top: 0,
    zIndex: 100,
    background: "var(--bg-header)",
    backdropFilter: "blur(12px)",
    borderBottom: "1px solid var(--border)",
    padding: "0 24px",
  },
  headerInner: {
    maxWidth: 1400,
    margin: "0 auto",
    display: "flex",
    alignItems: "center",
    gap: 12,
    height: 64,
  },
  logo: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    flexShrink: 0,
  },
  logoMark: {
    fontSize: 20,
    color: "var(--text)",
  },
  logoText: {
    fontSize: 18,
    fontWeight: 700,
    letterSpacing: "-0.5px",
    color: "var(--text)",
  },
  searchWrap: {
    flex: 1,
    position: "relative",
    display: "flex",
    alignItems: "center",
    background: "var(--bg-search)",
    borderRadius: 10,
    padding: "0 12px",
    maxWidth: 480,
  },
  searchIcon: {
    fontSize: 18,
    color: "var(--text-muted)",
    marginRight: 8,
    lineHeight: 1,
  },
  searchInput: {
    flex: 1,
    border: "none",
    background: "transparent",
    fontSize: 14,
    color: "var(--text)",
    outline: "none",
    padding: "10px 0",
    fontFamily: "inherit",
  },
  clearBtn: {
    background: "none",
    border: "none",
    cursor: "pointer",
    fontSize: 18,
    color: "var(--text-muted)",
    padding: "0 4px",
    lineHeight: 1,
  },
  searchSpinner: {
    width: 14,
    height: 14,
    borderRadius: "50%",
    border: "2px solid var(--border-ui)",
    borderTopColor: "var(--text)",
    animation: "spin 0.7s linear infinite",
    flexShrink: 0,
    marginLeft: 4,
  },
  headerRight: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    flexShrink: 0,
  },
  viewModes: {
    display: "flex",
    gap: 2,
    background: "var(--bg-search)",
    borderRadius: 9,
    padding: 3,
  },
  viewModeBtn: {
    background: "none",
    border: "none",
    borderRadius: 6,
    padding: "5px 10px",
    cursor: "pointer",
    fontSize: 13,
    color: "var(--text-muted)",
    fontFamily: "inherit",
    transition: "all 0.15s",
    lineHeight: 1,
  },
  viewModeBtnActive: {
    background: "var(--view-pill-bg)",
    color: "var(--text)",
    boxShadow: "0 1px 4px rgba(0,0,0,0.12)",
  },
  darkToggle: {
    background: "none",
    border: "1.5px solid var(--border-ui)",
    borderRadius: 8,
    padding: "7px 10px",
    cursor: "pointer",
    fontSize: 15,
    color: "var(--text-sec)",
    fontFamily: "inherit",
    transition: "all 0.2s",
    flexShrink: 0,
    lineHeight: 1,
  },
  favToggle: {
    display: "flex",
    alignItems: "center",
    gap: 6,
    background: "none",
    border: "1.5px solid var(--border-ui)",
    borderRadius: 8,
    padding: "7px 14px",
    cursor: "pointer",
    fontSize: 16,
    color: "var(--text-sec)",
    fontFamily: "inherit",
    transition: "all 0.2s",
    flexShrink: 0,
  },
  favToggleActive: {
    background: "var(--active-bg)",
    borderColor: "var(--active-bg)",
    color: "var(--active-text)",
  },
  favCount: {
    fontSize: 13,
    fontWeight: 600,
  },
  categories: {
    maxWidth: 1400,
    margin: "0 auto",
    display: "flex",
    gap: 8,
    padding: "10px 0 12px",
    overflowX: "auto",
    scrollbarWidth: "none",
  },
  catBtn: {
    background: "none",
    border: "1.5px solid var(--border-ui)",
    borderRadius: 20,
    padding: "5px 14px",
    fontSize: 13,
    fontWeight: 500,
    color: "var(--text-sec)",
    cursor: "pointer",
    whiteSpace: "nowrap",
    fontFamily: "inherit",
    transition: "all 0.15s",
  },
  catBtnActive: {
    background: "var(--active-bg)",
    borderColor: "var(--active-bg)",
    color: "var(--active-text)",
  },
  notice: {
    textAlign: "center",
    background: "var(--notice-bg)",
    color: "var(--notice-text)",
    fontSize: 13,
    padding: "10px 16px",
    borderBottom: "1px solid var(--notice-border)",
  },
  main: {
    maxWidth: 1400,
    margin: "0 auto",
    padding: "28px 24px 60px",
  },
  // Hero
  hero: {
    position: "relative",
    width: "100%",
    height: 420,
    overflow: "hidden",
    marginBottom: 28,
    borderRadius: 16,
    cursor: "pointer",
  },
  heroImg: {
    width: "100%",
    height: "100%",
    objectFit: "cover",
    display: "block",
  },
  heroOverlay: {
    position: "absolute",
    inset: 0,
    background: "linear-gradient(to top, rgba(0,0,0,0.75) 0%, rgba(0,0,0,0.15) 55%, transparent 100%)",
    display: "flex",
    flexDirection: "column",
    justifyContent: "flex-end",
    padding: "32px 36px",
  },
  heroLabel: {
    fontSize: 11,
    fontWeight: 600,
    letterSpacing: "1.5px",
    textTransform: "uppercase",
    color: "rgba(255,255,255,0.55)",
    marginBottom: 8,
  },
  heroTitle: {
    fontSize: 28,
    fontWeight: 800,
    color: "#fff",
    letterSpacing: "-0.5px",
    marginBottom: 6,
    textTransform: "capitalize",
    textShadow: "0 2px 12px rgba(0,0,0,0.4)",
  },
  heroPhotographer: {
    fontSize: 13,
    color: "rgba(255,255,255,0.65)",
    marginBottom: 20,
  },
  heroActions: {
    display: "flex",
    gap: 10,
  },
  heroBtn: {
    background: "rgba(255,255,255,0.15)",
    backdropFilter: "blur(8px)",
    border: "1px solid rgba(255,255,255,0.3)",
    borderRadius: 10,
    color: "#fff",
    fontSize: 13,
    fontWeight: 600,
    padding: "9px 20px",
    cursor: "pointer",
    fontFamily: "inherit",
    transition: "background 0.15s",
  },
  heroBtnPrimary: {
    background: "rgba(255,255,255,0.88)",
    color: "#111",
    borderColor: "transparent",
  },
  // Grid
  grid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fill, minmax(200px, 1fr))",
    gap: "16px",
  },
  gridLarge: {
    display: "grid",
    gridTemplateColumns: "repeat(2, 1fr)",
    gap: "16px",
  },
  // Card
  card: {
    position: "relative",
    borderRadius: 14,
    overflow: "hidden",
    background: "var(--bg-card)",
    aspectRatio: "9 / 16",
    cursor: "pointer",
    transition: "transform 0.2s ease, box-shadow 0.2s ease",
    boxShadow: "0 2px 8px rgba(0,0,0,0.06)",
  },
  cardHover: {
    transform: "translateY(-4px) scale(1.01)",
    boxShadow: "0 12px 32px rgba(0,0,0,0.14)",
  },
  imgWrap: {
    width: "100%",
    height: "100%",
    position: "relative",
  },
  imgPlaceholder: {
    position: "absolute",
    inset: 0,
    transition: "opacity 0.3s",
  },
  img: {
    width: "100%",
    height: "100%",
    objectFit: "cover",
    transition: "opacity 0.4s ease",
    display: "block",
  },
  cardOverlay: {
    position: "absolute",
    inset: 0,
    background: "linear-gradient(to top, rgba(0,0,0,0.6) 0%, transparent 55%)",
    display: "flex",
    flexDirection: "column",
    justifyContent: "flex-end",
    padding: 12,
    transition: "opacity 0.2s",
    pointerEvents: "none",
  },
  cardPhotographer: {
    fontSize: 11,
    color: "rgba(255,255,255,0.75)",
    fontWeight: 500,
    marginBottom: 6,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  previewBtn: {
    background: "rgba(255,255,255,0.15)",
    backdropFilter: "blur(8px)",
    border: "1px solid rgba(255,255,255,0.3)",
    borderRadius: 8,
    color: "#fff",
    fontSize: 12,
    fontWeight: 600,
    padding: "6px 0",
    cursor: "pointer",
    fontFamily: "inherit",
    letterSpacing: "0.3px",
    pointerEvents: "auto",
    marginBottom: 8,
  },
  cardIcons: {
    display: "flex",
    gap: 8,
    pointerEvents: "auto",
  },
  iconBtn: {
    width: 32,
    height: 32,
    borderRadius: 8,
    background: "rgba(255,255,255,0.15)",
    backdropFilter: "blur(8px)",
    border: "1px solid rgba(255,255,255,0.25)",
    color: "#fff",
    fontSize: 16,
    cursor: "pointer",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    lineHeight: 1,
    transition: "background 0.15s",
  },
  iconBtnFav: {
    background: "rgba(220,50,50,0.7)",
    borderColor: "rgba(220,50,50,0.5)",
  },
  iconBtnDone: {
    background: "rgba(40,180,80,0.65)",
    borderColor: "rgba(40,180,80,0.4)",
  },
  loadMore: {
    display: "flex",
    justifyContent: "center",
    padding: "40px 0 0",
  },
  spinner: {
    width: 28,
    height: 28,
    borderRadius: "50%",
    border: "2.5px solid var(--spinner-track)",
    borderTopColor: "var(--spinner-head)",
    animation: "spin 0.7s linear infinite",
  },
  empty: {
    textAlign: "center",
    padding: "100px 0",
  },
  emptyIcon: {
    fontSize: 48,
    color: "var(--border-ui)",
    marginBottom: 16,
  },
  emptyText: {
    fontSize: 18,
    fontWeight: 600,
    color: "var(--text)",
    margin: "0 0 8px",
  },
  emptySubtext: {
    fontSize: 14,
    color: "var(--text-muted)",
    margin: 0,
  },
  // Modal
  overlay: {
    position: "fixed",
    inset: 0,
    background: "rgba(0,0,0,0.88)",
    zIndex: 1000,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    padding: 24,
    backdropFilter: "blur(8px)",
    animation: "fadeIn 0.2s ease",
  },
  overlayContent: {
    position: "relative",
    maxHeight: "90vh",
    width: "min(900px, 90vw)",
    borderRadius: 20,
    overflow: "hidden",
    background: "#111",
    boxShadow: "0 40px 80px rgba(0,0,0,0.7)",
    display: "flex",
    flexDirection: "column",
  },
  previewImg: {
    width: "100%",
    maxHeight: "72vh",
    objectFit: "cover",
    display: "block",
    flexShrink: 0,
  },
  previewBar: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    padding: "16px 20px",
    background: "#111",
    borderTop: "1px solid rgba(255,255,255,0.06)",
    flexShrink: 0,
  },
  previewName: {
    margin: 0,
    fontSize: 14,
    fontWeight: 600,
    color: "#fff",
  },
  previewDesc: {
    margin: "3px 0 0",
    fontSize: 12,
    color: "#888",
    textTransform: "capitalize",
  },
  previewActions: {
    display: "flex",
    gap: 10,
  },
  actionBtn: {
    width: 40,
    height: 40,
    borderRadius: 10,
    background: "#222",
    border: "1px solid #333",
    color: "#aaa",
    fontSize: 18,
    cursor: "pointer",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    transition: "all 0.15s",
    fontFamily: "inherit",
  },
  actionBtnFav: {
    color: "#e74c3c",
    background: "#2a1515",
    borderColor: "#4a2020",
  },
  actionBtnDl: {
    color: "#fff",
    background: "#1a1a1a",
  },
  actionBtnDone: {
    color: "#4ade80",
    background: "#0a1f0a",
    borderColor: "#1a3a1a",
  },
  modalNav: {
    position: "absolute",
    top: "50%",
    transform: "translateY(-50%)",
    background: "rgba(0,0,0,0.45)",
    backdropFilter: "blur(6px)",
    border: "1px solid rgba(255,255,255,0.15)",
    color: "#fff",
    width: 44,
    height: 44,
    borderRadius: "50%",
    fontSize: 24,
    cursor: "pointer",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    zIndex: 10,
    transition: "background 0.15s",
  },
  closeBtn: {
    position: "absolute",
    top: 14,
    right: 14,
    width: 34,
    height: 34,
    borderRadius: "50%",
    background: "rgba(0,0,0,0.6)",
    border: "1px solid rgba(255,255,255,0.15)",
    color: "#fff",
    fontSize: 20,
    cursor: "pointer",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    lineHeight: 1,
    backdropFilter: "blur(4px)",
    zIndex: 20,
  },
};
