name: Release please

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  release:
    uses: ./.github/workflows/reusable-release-please.yml
    secrets: inherit
